stages:
    - test
    - build
    - build-docker-image

test:
    stage: test
    image: node:18.9.1-alpine3.16
    before_script:
        - npm install
    script:
        - npm run test:unit

build:
    stage: build
    image: node:18.9.1-alpine3.16
    before_script:
        - npm install
    needs:
        - test
    script:
        - npm run build

build-docker-image:
    stage: build-docker-image
    services:
        - name: docker:20.10.20-dind-alpine3.16
          alias: docker
    image: docker:20.10.20-alpine3.16
    script:
        - docker login -u $DOCKER_USERNAME --password ${DOCKER_PASSWORD}
        - docker build -t ${DOCKER_USERNAME}/frontend:$CI_COMMIT_SHORT_SHA .
        - docker tag ${DOCKER_USERNAME}/frontend:$CI_COMMIT_SHORT_SHA ${DOCKER_USERNAME}/frontend:latest
        - docker push ${DOCKER_USERNAME}/frontend:$CI_COMMIT_SHORT_SHA
        - docker push ${DOCKER_USERNAME}/frontend:latest
