name: Push on Main pipeline
run-name: ${{ github.actor }} test sa PR 🚀
on:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  Linter:
    runs-on: ubuntu-latest
    container: node:18.9.1-alpine3.16
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Start Linter
        run: npm run lint-check
  
  Tests:
    needs: Linter
    runs-on: ubuntu-latest
    container: node:18.9.1-alpine3.16
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Start Tests
        run: npm run test:unit
        
  Build:
    needs: Tests
    runs-on: ubuntu-latest
    container: node:18.9.1-alpine3.16
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
        
  Build-Docker-Image:
    needs: Build
    runs-on: ubuntu-latest
    container: docker:20.10.20-alpine3.16
    steps:
      - uses: actions/checkout@v4
      - name: Log on DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME  }} --password ${{ secrets.DOCKER_PASSWORD  }}
      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME  }}/frontend:$GITHUB_RUN_ID .
      - name: Add tag and push frontend image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME  }}/frontend:$GITHUB_RUN_ID ${{ secrets.DOCKER_USERNAME  }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME  }}/frontend:$GITHUB_RUN_ID
          docker push ${{ secrets.DOCKER_USERNAME  }}/frontend:latest